app/models.py
from app.extensions import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

"""
Users models
"""
class User(UserMixin, db.Model):

    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(150), nullable=False)
    password = db.Column(db.String(300), nullable=False)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

"""
Products models
"""

class Product(db.Model):

    __tablename__ = 'product'

    id_product = db.Column(db.Integer, primary_key = True)
    name_product = db.Column(db.String(100), nullable=True)
    price_product = db.Column(db.Integer, nullable=True)
    stock_product = db.Column(db.Integer, nullable=False)
    id_user = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    user = db.relationship('User', backref='product')

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField,IntegerField ,SubmitField
from wtforms.validators import DataRequired, Email, Length

"""
Definimos una clase por cada formulario:

"""


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(),Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('Register')


"""
Products forms
"""

class AddProduct(FlaskForm):
    name_product = StringField('Producto', validators=[DataRequired()])
    price_product = IntegerField('Precio', validators=[DataRequired()])
    stock_product = IntegerField('Stock', validators=[DataRequired()])
    submit = SubmitField('Agregar producto')

app/__init__.py
from flask import Flask         # Marco de trabajo principal de la app
from flask_sqlalchemy import SQLAlchemy  # Biblioteca para la interaccion con la base de datos
from flask_migrate import Migrate  # Extension que permite manejar las migraciones de la base de datos
from flask_login import LoginManager
from app.extensions import db, migrate, login_manager
"""
instanciamos SQLAlchemy y Migrate, que luego seran vinculadas a la app
flask
"""

# definir la funcion create_app


def create_app(config_class='app.config.Config'):

    """
    Esta función se usa para crear y configurar una instancia
    de la aplicacion Flask. Permite una configuracion flexible y reutilizable
    :param config_class:
    :return: instancia de la app
    """

    app = Flask(__name__)       # se crea una instancia de Flask
    app.config.from_object(config_class)    # la configuracion de la app se carga desde la clase de configuracion

    """
        Inicializar SQLAlchemy y Migrate con la app:
    """

    db.init_app(app)        # vincula la instancia SQLAlchemy con la app flask
    migrate.init_app(app, db) # vincula la instancia Migrate con la app flask y con la instancia SQLAlchemy para manejar migraciones
    login_manager.init_app(app)

    # Registrar blueprints
    from app.models import User
    from app.routes import bp as routes_bp
    app.register_blueprint(routes_bp)

    # redirige a la pagina de login si el usuario no esta autenticado
    login_manager.login_view = 'main.login'
    login_manager.login_message_category = 'info'


    return app  # retorna instancia de la app

@login_manager.user_loader
def load_user(user_id):
    from app.models import User
    return User.query.get(int(user_id))

app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash
from app import db
from app.models import User, Product
from app.forms import LoginForm, RegistrationForm, AddProduct
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required, current_user

bp = Blueprint('main', __name__)


"""
User routes
"""

@bp.route('/login', methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Login succesful', 'success')
            return redirect(url_for('main.index'))
        else:
            flash('Login failed. Check your email and/ or password','danger')

    return render_template('login.html', form=form)


@bp.route('/register', methods=['GET','POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        if form.password.data != form.confirm_password.data:
            flash('Password must match', 'danger')
            return redirect(url_for('main.register'))
        hashed_password = generate_password_hash(form.password.data)
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'succes')
        return redirect(url_for('main.login'))
    return render_template('register.html', form=form)

@bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out', 'info')
    return redirect(url_for('main.index'))


"""
Product routes
"""

@bp.route('/add', methods=['GET', 'POST'])
@login_required
def addProduct():

    form = AddProduct()

    if form.validate_on_submit():
        product = Product(
            name_product = form.name_product.data,
            price_product = form.price_product.data,
            stock_product = form.stock_product.data,
            id_user = current_user.id

        )

        db.session.add(product)
        db.session.commit()
        flash('Producto agregado exitosamente', 'succes')
        return redirect(url_for('main.index'))

    return render_template('addProduct.html', form=form)


@bp.route('/')
def index():
    return render_template('index.html')

app/templates/addProduct.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Agregar productos</h1>
    {% if current_user.is_authenticated %}
        <p>Hello, {{ current_user.username }}!</p>
        <p><a href="{{ url_for('main.logout') }}">Logout</a></p>
    {% else %}
        <p><a href="{{ url_for('main.login') }}">Login</a></p>
        <p><a href="{{ url_for('main.register') }}">Register</a></p>
    {% endif %}
    <main>
        <form method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.name_product.label }}<br>
                {{ form.name_product() }}
            </p>
            <p>
                {{ form.price_product.label }}<br>
                {{ form.price_product() }}<br>
            </p>
            <p>
                {{ form.stock_product.label }}<br>
                {{ form.stock_product() }}<br>
            </p>
            <p>
                {{ form.submit() }}
            </p>
        </form>
    </main>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Welcome to the Home Page</h1>
    {% if current_user.is_authenticated %}
        <p>Hello, {{ current_user.username }}!</p>
        <p><a href="{{ url_for('main.logout') }}">Logout</a></p>
    {% else %}
        <p><a href="{{ url_for('main.login') }}">Login</a></p>
        <p><a href="{{ url_for('main.register') }}">Register</a></p>
    {% endif %}
    <main>
        <a href="{{ url_for('main.addProduct') }}"> Cargar productos </a>
    </main>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email() }}<br>
            {% for error in form.email.errors %}
                <span>{{ error }}</span><br>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password() }}<br>
            {% for error in form.password.errors %}
                <span>{{ error }}</span><br>
            {% endfor %}
        </p>
        <p>
            {{ form.submit() }}
        </p>
    </form>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username() }}<br>
            {% for error in form.username.errors %}
                <span>{{ error }}</span><br>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email() }}<br>
            {% for error in form.email.errors %}
                <span>{{ error }}</span><br>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password() }}<br>
            {% for error in form.password.errors %}
                <span>{{ error }}</span><br>
            {% endfor %}
        </p>
        <p>
            {{ form.confirm_password.label }}<br>
            {{ form.confirm_password() }}<br>
            {% for error in form.confirm_password.errors %}
                <span>{{ error }}</span><br>
            {% endfor %}
        </p>
        <p>
            {{ form.submit() }}
        </p>
    </form>
</body>
</html>